# Generated by Django 4.1.7 on 2023-03-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_localadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organisationadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_portaluser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_securitypersonel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staffresident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ORGANISATION_ADMIN', 'ORGANISATION_ADMIN'), ('LOCAL_ADMIN', 'LOCAL_ADMIN'), ('PORTAL_USER ', 'PORTAL_USER'), ('  STAFF_RESIDENT', 'STAFF_RESIDENT'), ('SECURITY_PERSONEL', 'SECURITY_PERSONEL')], default='  STAFF_RESIDENT', max_length=30),
        ),
    ]
