# Generated by Django 4.1.7 on 2023-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='checkin_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='checkout_time',
            field=models.CharField(max_length=100),
        ),
    ]
