# Generated by Django 4.1.7 on 2023-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_alter_visitorlog_checkin_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_time', models.TimeField()),
                ('meeting_date', models.DateField()),
                ('meeting_duration_time', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=100, null=True)),
                ('pax', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=50)),
                ('laptop_serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('time_in', models.TimeField()),
                ('temperature', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
            ],
        ),
    ]
