# Generated by Django 4.1.7 on 2023-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_remove_user_created_on_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitypersonnel',
            old_name='vehicle_number',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='securitypersonnel',
            name='invite_date',
        ),
        migrations.RemoveField(
            model_name='securitypersonnel',
            name='invite_time',
        ),
        migrations.RemoveField(
            model_name='securitypersonnel',
            name='purpose',
        ),
        migrations.AddField(
            model_name='securitypersonnel',
            name='staff_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='securitypersonnel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securitypersonnel',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
