# Generated by Django 4.1.7 on 2023-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_user_is_localadmin_user_is_organisationadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invite_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
