# Generated by Django 3.2.6 on 2023-03-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_auto_20230306_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
