# Generated by Django 4.1.7 on 2023-04-04 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_rename_vehicle_number_securitypersonnel_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_log', models.BooleanField(default=False)),
                ('invite_code', models.BooleanField(default=False)),
                ('dashboard_view', models.BooleanField(default=False)),
                ('invites', models.BooleanField(default=False)),
                ('checkin', models.BooleanField(default=False)),
                ('hosts', models.BooleanField(default=False)),
                ('departments', models.BooleanField(default=False)),
                ('roles', models.BooleanField(default=False)),
                ('purpose', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='checker',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='is_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='subapp.roles'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organisationadmin', models.BooleanField(default=False)),
                ('is_localadmin', models.BooleanField(default=False)),
                ('is_securitypersonnel', models.BooleanField(default=False)),
                ('is_staffresident', models.BooleanField(default=False)),
                ('is_portaluser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
