# Generated by Django 4.1.7 on 2023-03-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_rename_vehicle_number_securitypersonnel_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('organisation_admin', 'view_organisations'), ('local_admin', 'view_local_organisations'), ('portal_users', 'view_portals'), ('staff_resident', 'view_staff_resident'), ('security_personell', 'view_security'))},
        ),
    ]
