# Generated by Django 4.1.7 on 2023-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_organisationcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaladmin',
            name='organisational_fields',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='checkin_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='checkout_time',
            field=models.DateTimeField(),
        ),
    ]
