# Generated by Django 4.1.7 on 2023-03-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_localadmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_organisationadmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_portaluser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_securitypersonel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staffresident',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles'),
        ),
    ]
