# Generated by Django 4.1.7 on 2023-03-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0004_remove_user_is_localadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationaladmin',
            name='password',
        ),
    ]
