# Generated by Django 4.1.7 on 2023-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0004_organisationaladmin_organisational_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationaladmin',
            name='organisational_fields',
            field=models.CharField(choices=[('first_name', 'first_name'), ('last_name', 'last_name'), ('visitor_id', 'visitor_id'), ('email', 'email'), ('meeting_time', 'meeting_time'), ('meeting_date', 'meeting_date'), ('meeting_duration_time', 'meeting_duration_time'), ('vehicle_number', 'vehicle_number'), ('pax', 'pax'), ('company_name', 'company_name'), ('purpose', 'purpose'), ('host', 'purpose'), ('laptop_serial_number', 'laptop_serial_number'), ('time_in', 'time_in'), ('temperature', 'temperature')], max_length=100),
        ),
    ]
