# Generated by Django 3.2.6 on 2023-03-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0005_alter_department_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='created_by',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='dob',
        ),
        migrations.AddField(
            model_name='registration',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.host'),
        ),
    ]
