# Generated by Django 4.1.7 on 2023-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0005_remove_user_role_user_is_localadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaladmin',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisationaladmin',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securitypersonnel',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staffresident',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffresident',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='securitypersonnel',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
