# Generated by Django 4.1.7 on 2023-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0005_alter_organisationaladmin_organisational_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='organisationaladmin',
            name='organisational_fields',
        ),
        migrations.AddField(
            model_name='organisationaladmin',
            name='fields',
            field=models.ManyToManyField(to='subapp.organisationfields'),
        ),
    ]
