# Generated by Django 4.1.7 on 2023-05-02 14:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0006_organisationfields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('First Name', 'First Name'), ('Last Name', 'Last Name'), ('Visitor ID', 'Visitor ID'), ('Email', 'Email'), ('Meeting Date', 'Meeting Date'), ('Meeting Time', 'Meeting Time'), ('Meeting Duration Time', 'Meeting Duration Time'), ('Vehicle Number', 'Vehicle Number'), ('Pax', 'Pax'), ('Company Name', 'Company Name'), ('Purpose', 'Purpose'), ('Host', 'Host'), ('Laptop Serial Number', 'Laptop Serial Number'), ('Time in', 'Time in'), ('Temperature', 'Tempterature'), ('Gender', 'Gender')], max_length=255, null=True),
        ),
    ]
