# Generated by Django 4.1.7 on 2023-05-11 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0007_organisation_organisation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationaladmin',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='checkout_time',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='is_in',
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checker',
            name='in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checker',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
