# Generated by Django 4.1.7 on 2023-03-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0007_alter_portaluser_email_alter_securitypersonnel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationaladmin',
            name='role',
            field=models.CharField(default='Organisation Admin', max_length=25, null=True),
        ),
    ]
