# Generated by Django 3.2.6 on 2023-03-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subapp', '0008_auto_20230307_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='register_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityregistration',
            name='register_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityregistration',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example1', to=settings.AUTH_USER_MODEL),
        ),
    ]
