# Generated by Django 3.2.6 on 2023-03-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0009_auto_20230307_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Security_Validation',
            new_name='Checker',
        ),
    ]
