# Generated by Django 4.1.7 on 2023-05-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0009_alter_visitorlog_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
