# Generated by Django 4.1.7 on 2023-05-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0010_alter_visitorlog_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('visitor_id', models.CharField(max_length=255)),
            ],
        ),
    ]
