# Generated by Django 4.1.7 on 2023-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0011_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='visitor_id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
