# Generated by Django 4.1.7 on 2023-03-14 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0012_companycustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('location_address', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('organisational_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('postal_address', models.CharField(max_length=100)),
                ('location_address', models.CharField(max_length=100)),
                ('organisation_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('maximum_branch', models.CharField(max_length=100)),
                ('organisational_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('roles', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('staff_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('localAdmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.localadmin')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(max_length=100)),
                ('invite_date', models.DateField()),
                ('invite_time', models.TimeField()),
                ('localAdmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.localadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('roles', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('staff_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('localAdmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.localadmin')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeregistration',
            name='department',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='check_in_and_out',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='invitation_create',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='invitation_send',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='registration_add',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='registration_delete',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='registration_edit',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='vistior_log',
        ),
        migrations.RemoveField(
            model_name='securityregistration',
            name='department',
        ),
        migrations.AddField(
            model_name='roles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.AddField(
            model_name='organisationaladmin',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subapp.organisationcategory'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles'),
        ),
        migrations.AddField(
            model_name='branches',
            name='Organisational_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.organisationaladmin'),
        ),
        migrations.AddField(
            model_name='branches',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subapp.organisation'),
        ),
    ]
