# Generated by Django 4.1.7 on 2023-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0012_remove_checkout_name_remove_checkout_visitor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='check_out',
        ),
        migrations.AddField(
            model_name='checkout',
            name='visitor_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='visitor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
