# Generated by Django 4.1.7 on 2023-05-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0013_remove_checkout_check_out_checkout_visitor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='visitor_name',
        ),
    ]
