# Generated by Django 4.1.7 on 2023-03-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0013_branches_localadmin_organisation_organisationaladmin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Resident',
            new_name='StaffResident',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='Organisational_admin',
            new_name='organisational_admin',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='user_id',
        ),
    ]
