# Generated by Django 4.1.7 on 2023-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0014_remove_checkout_visitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcheckin',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='host',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='meeting_duration_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='pax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcheckin',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
