# Generated by Django 4.1.7 on 2023-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0014_rename_staff_resident_staffresident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypersonnel',
            name='id_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='securitypersonnel',
            name='vehicle_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved')], default='Waiting', max_length=10),
        ),
    ]
