# Generated by Django 4.1.7 on 2023-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0015_securitypersonnel_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted')], default='Waiting', max_length=10),
        ),
    ]
