# Generated by Django 4.1.7 on 2023-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0015_alter_organisationcheckin_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='visitor_item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
