# Generated by Django 4.1.7 on 2023-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0017_rename_customer_name_localadmin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
