# Generated by Django 4.1.7 on 2023-03-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0018_homescreen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='staffresident',
            name='roles',
        ),
        migrations.AddField(
            model_name='localadmin',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles'),
        ),
        migrations.AddField(
            model_name='securitypersonnel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles'),
        ),
        migrations.AddField(
            model_name='staffresident',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles'),
        ),
    ]
