# Generated by Django 4.1.7 on 2023-03-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0019_remove_portaluser_roles_remove_staffresident_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localadmin',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('checkin_time', models.DateField()),
                ('checkout_time', models.TimeField()),
                ('checkin_from', models.TimeField()),
                ('vehicle_number', models.CharField(max_length=100, null=True)),
                ('pax', models.CharField(max_length=100, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subapp.roles')),
            ],
        ),
    ]
