# Generated by Django 4.1.7 on 2023-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0020_alter_localadmin_name_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
