# Generated by Django 4.1.7 on 2023-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0021_organisation_organisation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_email',
        ),
        migrations.AddField(
            model_name='organisationaladmin',
            name='organisation_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
