# Generated by Django 4.1.7 on 2023-03-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0022_remove_organisation_organisation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationaladmin',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='organisationaladmin',
            name='organisation_email',
        ),
        migrations.RemoveField(
            model_name='organisationaladmin',
            name='starting_date',
        ),
    ]
