# Generated by Django 4.1.7 on 2023-03-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0023_remove_organisationaladmin_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationaladmin',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='organisationaladmin',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='organisationaladmin',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
