# Generated by Django 4.1.7 on 2023-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0024_organisationaladmin_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localadmin',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
